- name: consul container
  shell:
    docker stop consul;docker rm consul;docker rmi progrium/consul; 
    docker run -d --name consul -h {{ ansible_hostname }} -v /mnt:/data \
    -p 192.168.33.10:8300:8300 \
    -p 192.168.33.10:8301:8301 \
    -p 192.168.33.10:8301:8301/udp \
    -p 192.168.33.10:8302:8302 \
    -p 192.168.33.10:8302:8302/udp \
    -p 192.168.33.10:8400:8400 \
    -p 192.168.33.10:8500:8500 \
    -p 172.17.0.1:153:53/udp \
    progrium/consul -server -advertise 192.168.33.10 -bootstrap-expect 1 -ui-dir /ui

- name: copy marathon json file to remote node
  copy: src=../files/registerservice_marathon.json dest=/tmp/

- name: register marathon gui with consul
  command: curl -X POST http://192.168.33.10:8500/v1/agent/service/register -d @/tmp/registerservice_marathon.json -H "Content-type{{':'}} application/json"

- name: copy consul json file to remote node
  copy: src=../files/registerservice_consul.json dest=/tmp/

- name: register consul gui with consul
  command: curl -X POST http://192.168.33.10:8500/v1/agent/service/register -d @/tmp/registerservice_consul.json -H "Content-type{{':'}} application/json"

- name: copy chronos json file to remote node
  copy: src=../files/registerservice_cron.json dest=/tmp/

- name: register chronos gui with consul
  command: curl -X POST http://192.168.33.10:8500/v1/agent/service/register -d @/tmp/registerservice_cron.json -H "Content-type{{':'}} application/json"
